/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description Return one page of products ordered by `(created_at, id)`.
         *
         *     `cursor` absent or the empty string means the first page. Any other query
         *     parameter is ignored. See `specs/S8.md` for the full contract.
         */
        get: operations["list_products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorResponse
         * @description The house validation-error response shape.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Field */
            field?: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * ProductListItem
         * @description One row of `GET /api/products`. Exactly these three keys.
         */
        ProductListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            stockLevel: components["schemas"]["StockLevelSummary"] | null;
        };
        /**
         * ProductsPage
         * @description A single keyset-paginated page of products.
         */
        ProductsPage: {
            /** Products */
            products: components["schemas"]["ProductListItem"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /**
         * StockLevelSummary
         * @description The single StockLevel shown for a Product in a list view.
         *
         *     See `docs/glossary.md`'s `Product.stockLevel` entry -- the row with the
         *     greatest `created_at`, ties broken by the greatest `id`; quantities are
         *     never summed across rows or measures.
         */
        StockLevelSummary: {
            /** Quantity */
            quantity: number;
            /**
             * Measure
             * @enum {string}
             */
            measure: "pieces" | "kilogram" | "gram" | "litre";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_products_api_products_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductsPage"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
